### PR TITLE
Use R2U to install r packages [no version bump]

### PR DESCRIPTION
**Pull request by henrykironde**

### CODE REVIEW

**Comment by henrykironde** [comment]
- [ ] Update DESCRIPTION contents
we removed install-packages.R since we use DESCRIPTION to Install R dependencies

with the github.event.pull_request.head.sha we fetch the real last commit during a PR, rather than the temporary commit.

```yml
- uses: actions/checkout@v3
        with:
          # pull_request ref https://github.com/orgs/community/discussions/28474
          ref: ${{ github.event.pull_request.head.sha }}

```
Hence, we are removing the check on PR 
`LOG: ${{ github.event_name == 'pull_request' && '$(git log --no-merges --format=%B -n 1 HEAD^2)' || '$(git log --no-merges --format=%B -n 1 HEAD)' }}`

- [ ] With the above change, we need to confirm if `Bump version` section of the CI log displayed the correct commit after  the PR merge.

**Comment by gmyenni** [comment]
Can you correct the title, authors and description to match: https://www.biorxiv.org/content/10.1101/332783v3.full
And the license to match the readme?

**Review by gmyenni — COMMENTED** [review]
It looks like the tests aren't running? Not sure if that's because there are so many notes and warnings in the R CMD check before it gets to run the actual tests.

Where is the update_data step?

**Comment by henrykironde** [comment]
I had missed update_data step. I have added it back and I made sure the tests run.

**Comment by gmyenni** [comment]
* It looks like every Rscript step gets this warning about the bspm: Warning message: D-Bus service not found!
* Do we need the R CMD check step? Because it isn't a package, it just creates a bunch of warnings and notes.

**Comment by gmyenni** [comment]
Also, the description in the the Description still needs to be updated. You can just use the abstract from the paper.

**Comment by ethanwhite** [comment]
There's an action available for this now:

```yml
      - name: Setup R
        uses: eddelbuettel/github-actions/r2u-setup@master
```

**Comment by ethanwhite** [comment]
Superseded by #540

**Pull request closed without merging**
