### PR TITLE
Try to recover weather data further back

### PR DESCRIPTION
**Pull request by ethanwhite**
Attempts to recover the weather data back to 2020-10-25 now that we've had some recover success.
Stores daily updates to this file in case we forget about it and the 4500 rows moves outside of the needed time window.

### CODE REVIEW

**Comment by ethanwhite** [comment]
Hopefully fixed now

**Comment by ethanwhite** [comment]
OK, now this should actually work :crossed_fingers:

**Comment by gmyenni** [comment]
Thanks!!

**Pull request merged**
