### PR TITLE
Cleaned 481 without tag scans, for annual report

### PR DESCRIPTION
**Pull request by diazrenata**
There weren't any mismatches with the tag scans, so the tag scans did not change any new data. 

We might as well merge this one instead of the 481-only branch, because this one includes the annual report table.

### CODE REVIEW

**Comment by bleds22e** [comment]
Did 481 get merged without the report? Also, it seems like the weather data is the issue with Travis. Maybe we close this and try again?

**Comment by ethanwhite** [comment]
I'm working on the weather data issue. Hope to have a temporary fix in by the end of the day.

**Comment by bleds22e** [comment]
Ah, ok. I wasn't sure if this had been resolved and there was another weather station issue or not. Gotcha.

**Comment by ethanwhite** [comment]
I sooo wish it was a weather station issue: https://github.com/weecology/PortalData/issues/276. Current status: spinning up a web server that will download the data daily and server the most recent version so that we can work with it consistently.

**Comment by diazrenata** [comment]
Oops, I think I was confusing.

I did this branch and generated the report in this branch, but it was provisional because the tag scans weren't in yet. I opened a different branch once the tag scans were up, but it turned out that there were no tag conflicts. I figured it made more sense to merge this older branch, with the report already done, than to make the report again in the new branch. So I closed the other pull request and left this one up. But the difference is minimal, and perhaps wasn't worth the convolutions 😛 Neither one has been merged yet.

**Comment by bleds22e** [comment]
No problem. I just wanted to make sure I was correctly interpreting what was happening.

Ellen K. Bledsoe
Ph.D. Candidate, Interdisciplinary Ecology
School of Natural Resources and Environment
Dept. of Wildlife Ecology and Conservation
University of Florida
ellen.bledsoe@ufl.edu<mailto:ellen.bledsoe@ufl.edu>




On Jan 2, 2019, at 6:33 PM, Renata Diaz <notifications@github.com<mailto:notifications@github.com>> wrote:


Oops, I think I was confusing.

I did this branch and generated the report in this branch, but it was provisional because the tag scans weren't in yet. I opened a different branch once the tag scans were up, but it turned out that there were no tag conflicts. I figured it made more sense to merge this older branch, with the report already done, than to make the report again in the new branch. So I closed the other pull request and left this one up. But the difference is minimal, and perhaps wasn't worth the convolutions 😛 Neither one has been merged yet.

**Comment by gmyenni** [comment]
This should pass now once you merge the recent changes to master.

**Pull request merged**
