### PR TITLE
Add rodents 502 [minor]

### PR DESCRIPTION
**Pull request by diazrenata**
Add rodent data for period 502 (and testing to see how checks go on this PR).

### CODE REVIEW

**Comment by diazrenata** [comment]
Sorry, did this create a problem? I'm trying to uncross the two branches.

**Comment by diazrenata** [comment]
To clarify (sorry, didn't realize you were online!):

The rodents_502 branch doesn't have the changes implemented in #433 so the tests fail. It also seems to have gotten stuck in actions somewhere, but that looks like a one-off actions problem. So I:
- Created a new branch off rodents_502 (this one)
- Updated it from main, to get the changes in #433 
- Added the version bump flag to the commit message
- Am now submitting a PR to trigger the checks 🤞

**Comment by gmyenni** [comment]
Looks like it did work over in #434 so I'm going to merge that one.

**Comment by diazrenata** [comment]
Sweet! 🎊

**Pull request closed without merging**
