### PR TITLE
data column issue

### PR DESCRIPTION
**Pull request by emchristensen**
Noticed that the "reprod" and "age" columns were reversed in the database from what they are on the data sheets -- this caused problems because when new data was  being appended it was being appended with those columns reversed, so we had "Z"s in age and "J"s in reprod.  I switched these values for the affected periods (447-450) and switched the columns so the database matches the data sheets.
But do check this to make sure I didn't accidentally screw something else up in the process...

### CODE REVIEW

**Comment by bleds22e** [comment]
Good catch!

**Comment by gmyenni** [comment]
Was this because they were old datasheets, from when the columns were mislabeled?

**Comment by emchristensen** [comment]
I have a vague memory that the columns got switched in order when I renamed them back when the data was on Serenity (actually it was Ethan who renamed them because I couldn't figure out how) but I didn't know how to switch them back so I hoped it would just be fine.  My bad.

**Comment by emchristensen** [comment]
I'm glad it's all on github now.  Much easier to work with.

**Pull request merged**
