### PR TITLE
Non recursive vector is an atomic object

### PR DESCRIPTION
**Pull request by henrykironde**
Use object['name-of-variable']

### CODE REVIEW

**Comment by henrykironde** [comment]
@gmyenni don't merge this PR,  but it looks like this works. 
I did not add `[skip ci]`

**Comment by henrykironde** [comment]
Note: I tested it with my master since we have a ` -git checkout master`. But the changes are in a Pull request. So this will still fail on PR's.

**Comment by gmyenni** [comment]
Awesome, thanks Henry! Is there still more to do?

**Comment by henrykironde** [comment]
I think that is it

**Pull request merged**
