### PR TITLE
add rodents_500[minor]

### PR DESCRIPTION
**Pull request by patdumandan**
can you review this for me @gmyenni ? Thanks!

### CODE REVIEW

**Comment by gmyenni** [comment]
For the replaced tag, can you put the original tag `C043B5` in the `ltag` column for the first entry too?

**Comment by gmyenni** [comment]
Also, you can merge `main` into this branch now and it should pass.

**Comment by patdumandan** [comment]
I think I was able to do those changes now. Can you check it one more time for me @gmyenni that I did them correctly?

**Comment by gmyenni** [comment]
Looks great, thanks!

**Pull request merged**
