### PR TITLE
Consolidated methods document

### PR DESCRIPTION
**Pull request by gmyenni**
Consolidated methods in SiteandMethods
Subdirectory READMEs contain descriptions of files

### CODE REVIEW

**Comment by gmyenni** [comment]
@ha0ye

**Comment by ha0ye** [comment]
Is SOP for another person to review and approve PRs? I can take a look tomorrow.

**Comment by ha0ye** [comment]
Looks great!

**Comment by gmyenni** [comment]
It is typically. Not for something this simple, but thought you might want to take a look.
Thanks!

**Pull request merged**
