### PR TITLE
portal_plants.csv combine

### PR DESCRIPTION
**Pull request by kvnamipara**
@gmyenni @ethanwhite 

- `Portal_plant_1981_2015.csv` and `Portal_plant_2015_present.csv` are merged to `Portal_plants.csv`
- added column `cover`
- use `update.py` to merge the files in future

### CODE REVIEW

**Comment by kvnamipara** [comment]
@gmyenni
- cf column added to `Portal_plants.csv`
- `update.py` updated for column cf

**Comment by kvnamipara** [comment]
@gmyenni 
Please review this PR and update ASAP. We want to use dataset for DataRetriever.

**Comment by ethanwhite** [comment]
> Please review this PR and update ASAP. We want to use dataset for DataRetriever.

@kvnamipara - I really appreciate that you're excited to proceed, but that doesn't oblige other people to rush. The current version of this PR has only been in for 12 hours. As I mentioned in our issue you can just use `Portal_plant_2015_present.csv` in the Data Retriever for now since it has the right structure and we can swap the name out once there is a single file.

Also, looking at this I don't see any need to include the script that made these changes in this repo, so I would recommend removing that from this PR to increase they chances they can easily merge in the data change that is of interest.

**Comment by kvnamipara** [comment]
@gmyenni Thank you!

**Pull request merged**
